#!/usr/bin/env bash

FILE=$1
target=$2
re='^[0-9]+$'
match=1
run=0

echo "runs","fvalue","runtime"

while IFS="" read -r p || [ -n "$p" ]
do
    if ! [[ $match ]]; then
        continue
    fi

    IFS=' ' read -r -a array <<< $p
    runtime=${array[0]}

    if ! [[ $runtime =~ $re ]]; then 
        match=1
        (( run++ ))
        continue
    fi 
    
    fvalue=$(awk '{ print $1+0 }' <<< ${array[2]})
    
    if [[ $fvalue -ge $target && $match -eq 1 ]]; then
        echo $run,$fvalue,$runtime
        match=0
    fi
done < $1 
