# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align_by_target_inner_loop <- function(t, idxEvals, idxTarget, data, index, next_lines, curr_eval, maximization) {
    .Call('_IOHProfiler_align_by_target_inner_loop', PACKAGE = 'IOHProfiler', t, idxEvals, idxTarget, data, index, next_lines, curr_eval, maximization)
}

c_impute <- function(x, y, rowname) {
    .Call('_IOHProfiler_c_impute', PACKAGE = 'IOHProfiler', x, y, rowname)
}

c_impute_runtime <- function(index, value, FV, maximization) {
    .Call('_IOHProfiler_c_impute_runtime', PACKAGE = 'IOHProfiler', index, value, FV, maximization)
}

#' Align a dataSetList by runtime
#'
#' @param data the data
#' @param FV Function values
#' @param idxValue index of the function values
#' @param maximization Boolean
#' @param idxTarget index of the target
#'
#' @export
c_align_runtime <- function(data, FV, idxValue, maximization, idxTarget) {
    .Call('_IOHProfiler_c_align_runtime', PACKAGE = 'IOHProfiler', data, FV, idxValue, maximization, idxTarget)
}

c_read_dat <- function(dat, NC, leading) {
    .Call('_IOHProfiler_c_read_dat', PACKAGE = 'IOHProfiler', dat, NC, leading)
}

