# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

align_by_target_inner_loop <-
  function(t,
           idxEvals,
           idxTarget,
           data,
           index,
           next_lines,
           curr_eval,
           maximization) {
    .Call(
      '_IOHanalyzer_align_by_target_inner_loop',
      PACKAGE = 'IOHanalyzer',
      t,
      idxEvals,
      idxTarget,
      data,
      index,
      next_lines,
      curr_eval,
      maximization
    )
  }

c_impute <- function(x, y, rowname) {
  .Call('_IOHanalyzer_c_impute', PACKAGE = 'IOHanalyzer', x, y, rowname)
}

c_impute_running_time <- function(index, value, FV, maximization) {
  .Call('_IOHanalyzer_c_impute_running_time',
        PACKAGE = 'IOHanalyzer',
        index,
        value,
        FV,
        maximization)
}

#' Align a list of data set by function values
#'
#' @param data the data
#' @param FV Function values
#' @param idxValue index of the function values
#' @param maximization Boolean
#' @param idxTarget index of the target
#' @noRd
c_align_running_time <-
  function(data,
           FV,
           idxValue,
           maximization,
           idxTarget) {
    .Call(
      '_IOHanalyzer_c_align_running_time',
      PACKAGE = 'IOHanalyzer',
      data,
      FV,
      idxValue,
      maximization,
      idxTarget
    )
  }

#' Align a matrix of data set by function values
#'
#' @param data the data
#' @param FV Function values
#' @param IdxValues The index values
#' @param maximization Boolean
#' @noRd
c_align_running_time_matrix <-
  function(data, FV, IdxValues, maximization) {
    .Call(
      '_IOHanalyzer_c_align_running_time_matrix',
      PACKAGE = 'IOHanalyzer',
      data,
      FV,
      IdxValues,
      maximization
    )
  }

c_read_dat <- function(dat, NC, leading) {
  .Call('_IOHanalyzer_c_read_dat', PACKAGE = 'IOHanalyzer', dat, NC, leading)
}
